# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7002
  connection-timeout: 5000ms
  servlet:
    context-path: /rocket-mq

spring:
  application:
    name: rocket-mq
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true