# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7007
  connection-timeout: 5000ms

spring:
  application:
    name: ware-elastic-search
  data:
    elasticsearch:
      # 默认 elasticsearch
      cluster-name: elasticsearch
      # 9200作为Http协议，主要用于外部通讯
      # 9300作为Tcp协议，jar之间就是通过tcp协议通讯
      cluster-nodes: 192.168.72.130:9300
